### ISSUE TITLE
Cannot inline bytecode built with JVM target 17

### ISSUE THREAD

**Issue by brsuslcn** [sebaslogen/resaca#137] opened 2024-09-03 11:31 UTC
I use this library in my projects, especially when I use ViewModel in ModalBottomSheets and composables that don't have navigation. For one of my projects, I cannot use it because I get a javaTarget error. I have already set the javaTarget to 17, and I have tried invalidating caches and cleaning the project, but none of them worked. I am using Hilt version 2.51.1 and Resaca-Hilt version 4.1.3.

Java Target:
![ss2](https://github.com/user-attachments/assets/ebe702c3-5a7b-4781-a6c0-6e577e4a9618)
 
 The error:
![ss1](https://github.com/user-attachments/assets/428585cd-0d9f-496b-a9aa-8012a2800cd2)

**Comment by sebaslogen** [comment] 2024-09-03 13:24
Maybe it´s related to `kotlinOptions` being deprecated and replaced with `compilerOptions` 🤔 

Have you tried using the new Kotlin API for this? https://stackoverflow.com/a/77903418/5250468
That's the API I also use in the resaca codebase https://github.com/sebaslogen/resaca/blob/7b089923036c0e517ffb0e979a4e6679dbc8d03a/build.gradle.kts#L48

**Comment by brsuslcn** [comment] 2024-09-03 13:43
> Maybe it's related to `kotlinOptions` being deprecated and replaced with `compilerOptions` 🤔
> 
> Have you tried using the new Kotlin API for this? https://stackoverflow.com/a/77903418/5250468 That's the API I also use in the resaca codebase
> 
> https://github.com/sebaslogen/resaca/blob/7b089923036c0e517ffb0e979a4e6679dbc8d03a/build.gradle.kts#L48


I applied everything, but none of them are working. This dependency cannot correctly identify if the Java version is 17; it always detects it as Java version 1.8

**Comment by sebaslogen** [comment] 2024-09-03 14:15
> > Maybe it's related to `kotlinOptions` being deprecated and replaced with `compilerOptions` 🤔
> > Have you tried using the new Kotlin API for this? https://stackoverflow.com/a/77903418/5250468 That's the API I also use in the resaca codebase
> > https://github.com/sebaslogen/resaca/blob/7b089923036c0e517ffb0e979a4e6679dbc8d03a/build.gradle.kts#L48
> 
> I applied everything, but none of them are working. This dependency cannot correctly identify if the Java version is 17; it always detects it as Java version 1.8

Then I'm out of ideas, maybe if you share your code I can take a look, but if you say other projects work for you, I assume the problem is somewhere in that specific project's configuration.

**Comment by sebaslogen** [comment] 2024-09-03 14:18
Ah, one more thing, the JDK that compiles your project has to be 17 or newer, you can check just in case with `java --version`

**Comment by brsuslcn** [comment] 2024-09-03 14:30
Yeah, I know, I'm using the latest Java version. It works for other projects, but not for one of them. I think it's related to KSP or Kotlin DSL. I'll also try downgrading the AGP version

**Comment by sebaslogen** [comment] 2024-10-31 18:35
Since there were no updates on this issue in a while for your specific project, I'm closing this for now. If you have any new info or updates, please feel free to reopen.

**Closed by sebaslogen** 2024-10-31 18:35 UTC
Labels: question, dependencies
